/**
 * Auto-generated affiliate store config for robotjakt.
 * Channel: 2063681412 (Adtraction), 3467327 (Addrevenue).
 * Generated by scripts/setup-multistore-cta.mjs from product feeds.
 */

export interface AffiliateStore {
  name: string;
  commission: number;
  network: 'adtraction' | 'addrevenue' | 'awin' | 'direct';
  baseUrl: string;
  searchUrl?: string;
  buildUrl: (targetUrl: string) => string;
}

export const AFFILIATE_STORES: Record<string, AffiliateStore> = {
  'CSMegastore': {
    name: 'CSMegastore',
    commission: 0.05,
    network: 'adtraction',
    baseUrl: 'https://www.csmegastore.se',
    searchUrl: 'https://www.csmegastore.se/?q={q}',
    buildUrl: (t) => `https://track.adtraction.com/t/t?a=1514097158&c=2063681412&p=1&s=&url=${encodeURIComponent(t)}`,
  },
  'Elon': {
    name: 'Elon',
    commission: 0.05,
    network: 'adtraction',
    baseUrl: 'https://www.elon.se',
    searchUrl: 'https://www.elon.se/?q={q}',
    buildUrl: (t) => `https://track.adtraction.com/t/t?a=1606750990&c=2063681412&p=1&s=&url=${encodeURIComponent(t)}`,
  },
  'Estore': {
    name: 'Estore',
    commission: 0.05,
    network: 'adtraction',
    baseUrl: 'https://www.estore.nu',
    searchUrl: 'https://www.estore.nu/?q={q}',
    buildUrl: (t) => `https://track.adtraction.com/t/t?a=1954032577&c=2063681412&p=1&s=&url=${encodeURIComponent(t)}`,
  },
  'Kjell & Company': {
    name: 'Kjell & Company',
    commission: 0.05,
    network: 'adtraction',
    baseUrl: 'https://www.kjell.com',
    searchUrl: 'https://www.kjell.com/?q={q}',
    buildUrl: (t) => `https://track.adtraction.com/t/t?a=1098281528&c=2063681412&p=1&s=&url=${encodeURIComponent(t)}`,
  },
  'Komplett': {
    name: 'Komplett',
    commission: 0.05,
    network: 'adtraction',
    baseUrl: 'https://www.komplett.se',
    searchUrl: 'https://www.komplett.se/?q={q}',
    buildUrl: (t) => `https://track.adtraction.com/t/t?a=1615916037&c=2063681412&p=1&s=&url=${encodeURIComponent(t)}`,
  },
  'Proshop': {
    name: 'Proshop',
    commission: 0.05,
    network: 'adtraction',
    baseUrl: 'https://www.proshop.se',
    searchUrl: 'https://www.proshop.se/?q={q}',
    buildUrl: (t) => `https://track.adtraction.com/t/t?a=1870484628&c=2063681412&p=1&s=&url=${encodeURIComponent(t)}`,
  },
  'Teknikproffset': {
    name: 'Teknikproffset',
    commission: 0.05,
    network: 'adtraction',
    baseUrl: 'https://www.teknikproffset.se',
    searchUrl: 'https://www.teknikproffset.se/?q={q}',
    buildUrl: (t) => `https://track.adtraction.com/t/t?a=1954032645&c=2063681412&p=1&s=&url=${encodeURIComponent(t)}`,
  },
  'Dronarbutiken': {
    name: 'Dronarbutiken',
    commission: 0.05,
    network: 'addrevenue',
    baseUrl: 'https://www.dronarbutiken.se',
    searchUrl: 'https://www.dronarbutiken.se/?q={q}',
    buildUrl: (t) => `https://addrevenue.io/t?a=987736&c=3467327&url=${encodeURIComponent(t)}`,
  },
  'Villanytt': {
    name: 'Villanytt',
    commission: 0.05,
    network: 'addrevenue',
    baseUrl: 'https://www.villanytt.se',
    searchUrl: 'https://www.villanytt.se/?q={q}',
    buildUrl: (t) => `https://addrevenue.io/t?a=984922&c=3467327&url=${encodeURIComponent(t)}`,
  },
  'Robot-dammsugaren': {
    name: 'Robot-dammsugaren',
    commission: 0.05,
    network: 'addrevenue',
    baseUrl: 'https://www.robot-dammsugaren.se',
    searchUrl: 'https://www.robot-dammsugaren.se/?q={q}',
    buildUrl: (t) => `https://addrevenue.io/t?a=985815&c=3467327&url=${encodeURIComponent(t)}`,
  },
  'Robotrent': {
    name: 'Robotrent',
    commission: 0.05,
    network: 'addrevenue',
    baseUrl: 'https://www.robotrent.se',
    searchUrl: 'https://www.robotrent.se/?q={q}',
    buildUrl: (t) => `https://addrevenue.io/t?a=985383&c=3467327&url=${encodeURIComponent(t)}`,
  },
  'Neatsvor': {
    name: 'Neatsvor',
    commission: 0.05,
    network: 'addrevenue',
    baseUrl: 'https://www.neatsvor.se',
    searchUrl: 'https://www.neatsvor.se/?q={q}',
    buildUrl: (t) => `https://addrevenue.io/t?a=985945&c=3467327&url=${encodeURIComponent(t)}`,
  },
};

export function getStore(storeName: string): AffiliateStore | undefined {
  if (!storeName) return undefined;
  const direct = AFFILIATE_STORES[storeName];
  if (direct) return direct;
  const normalized = storeName.trim().toLowerCase();
  for (const [key, store] of Object.entries(AFFILIATE_STORES)) {
    if (key.toLowerCase() === normalized) return store;
    if (store.name.toLowerCase() === normalized) return store;
  }
  return undefined;
}

export function buildSearchDeeplink(storeName: string, query: string): string | undefined {
  const store = getStore(storeName);
  if (!store?.searchUrl) return undefined;
  const targetUrl = store.searchUrl.replace('{q}', encodeURIComponent(query));
  return store.buildUrl(targetUrl);
}

export function buildProductDeeplink(storeName: string, productPageUrl: string): string | undefined {
  const store = getStore(storeName);
  if (!store) return undefined;
  return store.buildUrl(productPageUrl);
}
