/**
 * Auto-generated affiliate store config for robotjakt.
 * Channel: 2063681412 (Adtraction), 3467327 (Addrevenue).
 * Generated by scripts/setup-multistore-cta.mjs from product feeds.
 */

export interface AffiliateStore {
  name: string;
  commission: number;
  network: 'adtraction' | 'addrevenue' | 'awin' | 'direct';
  baseUrl: string;
  searchUrl?: string;
  /**
   * @deprecated Använd aldrig denna funktion. Bevarad endast för bakåtkompatibilitet
   * med gammal kod. Returnerar alltid undefined så att hallucinerade tracker-URL:er
   * aldrig kan genereras. Använd `resolveTrackedUrl` från `lib/cta-resolver.ts` istället.
   */
  buildUrl: (targetUrl: string) => string | undefined;
}

// Verkliga provisioner (verifierade 2026-05-22):
// Elon 5%, Kjell 5%, Komplett 4%, CS Megastore 4%, Proshop 3.2%, Addrevenue ~3%
export const AFFILIATE_STORES: Record<string, AffiliateStore> = {
  // Aktiva Adtraction-butiker (nyckel matchar FEED_BY_STORE och BRAND_TO_STORES)
  'Elon': {
    name: 'Elon',
    commission: 0.05,
    network: 'adtraction',
    baseUrl: 'https://www.elon.se',
    searchUrl: 'https://www.elon.se/sok?q={q}',
    buildUrl: () => undefined,
  },
  'Kjell & Company': {
    name: 'Kjell',
    commission: 0.05,
    network: 'adtraction',
    baseUrl: 'https://www.kjell.com',
    searchUrl: 'https://www.kjell.com/se/sok?query={q}',
    buildUrl: () => undefined,
  },
  'Komplett': {
    name: 'Komplett',
    commission: 0.04,
    network: 'adtraction',
    baseUrl: 'https://www.komplett.se',
    searchUrl: 'https://www.komplett.se/search/?query={q}',
    buildUrl: () => undefined,
  },
  'CS MEGASTORE': {
    name: 'CS Megastore',
    commission: 0.04,
    network: 'adtraction',
    baseUrl: 'https://www.csmegastore.se',
    searchUrl: 'https://www.csmegastore.se/?q={q}',
    buildUrl: () => undefined,
  },
  // Alias: BRAND_TO_STORES använder 'CSMegastore' (ihopskrivet)
  'CSMegastore': {
    name: 'CS Megastore',
    commission: 0.04,
    network: 'adtraction',
    baseUrl: 'https://www.csmegastore.se',
    searchUrl: 'https://www.csmegastore.se/?q={q}',
    buildUrl: () => undefined,
  },
  'Proshop': {
    name: 'Proshop',
    commission: 0.032,
    network: 'adtraction',
    baseUrl: 'https://www.proshop.se',
    searchUrl: 'https://www.proshop.se/?search={q}',
    buildUrl: () => undefined,
  },
  // Aktiva Addrevenue-butiker (~3%)
  'Dronarbutiken': {
    name: 'Dronarbutiken',
    commission: 0.03,
    network: 'addrevenue',
    baseUrl: 'https://www.dronarbutiken.se',
    searchUrl: 'https://www.dronarbutiken.se/?q={q}',
    buildUrl: () => undefined,
  },
  'Robot-dammsugaren': {
    name: 'Robot-dammsugaren',
    commission: 0.03,
    network: 'addrevenue',
    baseUrl: 'https://www.robot-dammsugaren.se',
    searchUrl: 'https://www.robot-dammsugaren.se/?q={q}',
    buildUrl: () => undefined,
  },
  'Robotrent': {
    name: 'Robotrent',
    commission: 0.03,
    network: 'addrevenue',
    baseUrl: 'https://www.robotrent.se',
    searchUrl: 'https://www.robotrent.se/?q={q}',
    buildUrl: () => undefined,
  },
  'Neatsvor': {
    name: 'Neatsvor',
    commission: 0.03,
    network: 'addrevenue',
    baseUrl: 'https://www.neatsvor.se',
    searchUrl: 'https://www.neatsvor.se/?q={q}',
    buildUrl: () => undefined,
  },
};

export function getStore(storeName: string): AffiliateStore | undefined {
  if (!storeName) return undefined;
  const direct = AFFILIATE_STORES[storeName];
  if (direct) return direct;
  const normalized = storeName.trim().toLowerCase();
  for (const [key, store] of Object.entries(AFFILIATE_STORES)) {
    if (key.toLowerCase() === normalized) return store;
    if (store.name.toLowerCase() === normalized) return store;
  }
  return undefined;
}

/**
 * @deprecated Använd resolveTrackedUrl från lib/cta-resolver.ts istället.
 * Kvar för bakåtkompat, re-exporteras från cta-resolver. Använd inte direkt.
 */
export { buildSearchDeeplink, buildProductDeeplink } from '../lib/cta-resolver';
